name: Python CI/CD

on:
  push:
    branches: [ main ] # Ou a branch principal do seu repositório

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11' 

    - name: Validate Python code
      run: python -m py_compile src/server.py

    

    - name: Trigger Render Deploy Hook
      if: github.ref == 'refs/heads/main' && success()
      env:
        RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: |
        if [ -z "$RENDER_DEPLOY_HOOK_URL" ]; then
          echo "RENDER_DEPLOY_HOOK_URL secret not set. Skipping deployment."
        else
          curl -X POST $RENDER_DEPLOY_HOOK_URL
          echo "Render deploy hook triggered."
        fi

