name: Python CI/CD

on:
  push:
    branches: [ main ] # Ou a branch principal do seu repositório

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11' # Use a versão do Python compatível com seu código

    # Não há dependências externas, então pulamos a instalação
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Validate Python code
      run: python -m py_compile src/server.py

    # Adicione aqui etapas de teste se você tiver testes automatizados
    # - name: Run tests
    #   run: |
    #     python -m unittest discover tests

    - name: Trigger Render Deploy Hook
      # Só executa o deploy se o código for válido e estiver na branch main
      if: github.ref == 'refs/heads/main' && success()
      env:
        RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: |
        if [ -z "$RENDER_DEPLOY_HOOK_URL" ]; then
          echo "RENDER_DEPLOY_HOOK_URL secret not set. Skipping deployment."
        else
          curl -X POST $RENDER_DEPLOY_HOOK_URL
          echo "Render deploy hook triggered."
        fi

